---

- name: ensure input folder exists
  file: path={{ input_dir }} state=directory

- name: ensure output folder exists
  file: path={{ output_dir }} state=directory

- name: copy the count/ps/url/proxy data file to the target server
  copy: src={{ src_dir }} dest={{ nfs_dir }}/input owner=fogetti group=fogetti backup=yes

- name: copy the jar file to the target server
  copy: src={{ jar_dir }}/{{ jar_file }} dest={{ topology_jar }} owner=fogetti group=fogetti backup=yes

- name: generate storm env ini
  template: src=storm_env.ini.j2 dest={{ conf_dir }}/storm_env.ini

- name: list all topologies
  command: "{{ storm_binary }} list"
  register: list_toplogies

- name: kill the topology
  command: "{{ storm_binary }} kill {{ topology_name }}"
  when: (list_toplogies.stdout_lines|last != "No topologies running.") and
        (list_toplogies.stdout.find('phish-storm') != -1)

- name: start the topology
  command: "{{ storm_binary }} jar {{ topology_jar }} {{ main_class }}"
  register: start_topology
  until: start_topology.stdout.find("RuntimeException") == -1
  retries: 3
  environment:
    JAVA_HOME: /usr