---

- name: ensure input folder exists
  file: path={{ input_dir }} state=directory

- name: copy the count/ps/url data file to the target server
  copy: src={{ src_dir }} dest={{ input_dir }} owner=fogetti group=fogetti backup=yes

- name: copy the jar file to the target server
  copy: src={{ jar_dir }}/{{ jar_file }} dest={{ topology_jar }} owner=fogetti group=fogetti backup=yes

- name: generate storm env ini
  template: src=storm_env.ini.j2 dest={{ conf_dir }}/storm_env.ini

- name: start the topology
  command: sh {{ storm_binary }} jar {{ topology_jar }} {{ main_class }}
  environment:
    JAVA_HOME: /usr
